STATIC_DIR = "static"
"""Name of the static directory"""
STATIC_PATH = "/static"
"""Path static files are served from"""
FAVICON_PATH = f"{STATIC_PATH}/starlite-favicon.ico"
"""Name of the favicon file in the static directory"""
